### ISSUE TITLE
State cannot be accessed in init hook in Ember 3.5.1

### ISSUE THREAD

**Issue by BobrImperator** [ember-redux/ember-redux#180]
I use ember-redux on a project, and ocassionally I need to make a request from `init` hook which uses some data from the global state, currently I'm on `Ember 3.1.1` and trying to update to `3.5.1`, but the problem I've encountered holds me down.

Potentially changing a single line in `connect.js` fixes the problem:

`if (WrappedComponent.hasOwnProperty('extend')) {`  ->    `if (WrappedComponent.extend) {`
Because of when the call to the store is made. 
In `ember-object` [connector](https://github.com/ember-redux/ember-redux/blob/master/addon/ember-object.js), it happens before `WrappedComponent`'s `init` hook,
while for [`es-2015`](https://github.com/ember-redux/ember-redux/blob/master/addon/es2015-class.js), [`es-2019`](https://github.com/ember-redux/ember-redux/blob/master/addon/es2019-class.js) it happens later.

I've prepared a reproduction of the problem:
https://github.com/BobrImperator/redux-state-in-init

**Comment by toranb** [comment]
@BobrImperator appreciate you opening this! I've spent a little time today trying to get this fixed without breaking older versions of ember and this seemingly trivial ask has proved to be a surprisingly uphill battle given all the churn es2015 class syntax has seen over the last 12+ months. I'll update you more next week when I take another look at this ;)

**Comment by BobrImperator** [comment]
Actually, the `es-2019` version might work when the state call hook was to be moved above `super`, although I'm not sure if it might be breaking something.
The `es-2015` though seems to be failing because We cannot call the `state` call before `super`.

I'm also not sure, but I've read somewhere, that Ember will continue initializing with `init`, but that's an open topic right now.

**Comment by toranb** [comment]
@BobrImperator I was able to solve it (even for 2.18 despite what Travis said during the PR build)

https://github.com/ember-redux/ember-redux/pull/182

I'll need to build a fresh 2.18 ember-cli app quick to confirm it's g2g but if so (fingers crossed) I'll publish a new version of this library next week. Can you confirm the master branch of this fixes your use case? I tried to take your example and throw that into the app as a test case (to confirm this is working for EmberObject from ember 2.18+)

**Comment by BobrImperator** [comment]
I can confirm that this works for `3.5.1` `3.6` and latest `3.8.0` Ember!
Sweet, thank you very much!

But *I think* that the test You've written might not detect a regression to this behaviour, I dunno what the `state` is in your example, but in mine, I rely on an exception that would be raised when trying to access a object's key, which during `init` time was `undefined` before.
That's why in my tests I returned an object from state, and tried to access its values.

**Comment by toranb** [comment]
@BobrImperator I had a failing test before I made this change so I think we are good :)

I just published v4.0.2 to npm so give that a go when you get time! Thanks again for reporting this!

**Comment by toranb** [comment]
note: I was able to confirm this version works fine w/ ember v2.15 by upgrading my older TODOMVC app

https://github.com/toranb/ember-redux-todomvc/commits/master

**Comment by BobrImperator** [comment]
Sadly, the issue is back, but in production instead, it hits the `es-2015 connector` thus reproducing the problem.
Is moving the `core` calls before life-cycle hooks a breaking change?
Also worth to notice, that it hits the `es-2015` despite component being used in *classic* way.

I think that also for the `es-2015` it would be beneficial to use an `init` hook as well, since they're still a go to way.
